name: typerun
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    environment:
      DOMAIN: ${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - transcendence
    restart: always
    depends_on:
      - frontend
      - backend
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    container_name: frontend
    build: 
      context: ./requirements/frontend
      dockerfile: Dockerfile
    expose: 
      - "5173"
    volumes:
      - frontend_node_modules:/app/node_modules
      - ./requirements/backend:/backend
    networks:
      - transcendence
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    container_name: backend
    build:
      context: ./requirements/backend
      dockerfile: Dockerfile
    environment:
      - FORTYTWO_CALLBACK_URL=https://${DOMAIN}/api/auth/42/callback
      - FRONTEND_URL=https://${DOMAIN}
      - NODE_ENV=production
    expose:
      - "3000"
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - ./requirements/backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - transcendence
    restart: always
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  postgresql:
    container_name: postgresql
    build:
      context: ./requirements/postgresql
      dockerfile: Dockerfile
    expose:
      - "5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - transcendence
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgresql_data:
  backend_node_modules:
  frontend_node_modules:


networks:
  transcendence:
    driver: bridge
    name: transcendence